- name: installing somethinggggggggg
  hosts: myserver
  become: true
  tasks:
    - name: installing nginx
      yum:
       name: ['nginx', 'mariadb105-server', 'php-fpm']
       state: present

    - name: starting nginx
      service:
       name: nginx
       state: started

    - name: starting mariadb
      service:
        name: mariadb
        state: started

    - name: starting php-fpm
      service: name=php-fpm state=started

    - name: restart all
      service: name=nginx state=restarted
      service: name=mariadb state=restarted
      service: name=php-fpm state=restarted
