- name: installing somethinggggggggg
  hosts: myserver
  become: true
  tasks:
    - name: installing nginx
      yum:
       name: nginx
       state: present

 

    - name: starting nginx
      service:
       name: nginx
       state: started
