- name: installing somethinggggggggg
  hosts: myserver
  become: true
  tasks:
    - name: update package
      yum: 
        name: '*'
        state: latest
      when: ansible_distribution== 'Amazon'

    - name: update package
      yum:
        name: '*'
        state: latest
      when: ansible_distribution== 'ubuntu'

    - name: installing nginx
      yum:
       name: nginx
       state: present

      when: ansible_distribution== 'Amazon'

    - name: instaling nginx
      apt:
       name: nginx
       state: present

      when: ansible_distribution== 'ubuntu'

    - name: starting nginx
      service:
        name: nginx
        state: started
      when: ansible_distribution== 'Amazon'

    - name: starting nginx
      service:
        name: nginx
        state: started
      when: ansible_distribution== 'Amazon'

    - name: instlling mariadb105-server
      yum:
        name: mariadb105-server
        state: present
      when: ansible_distribution== 'Amazon'

    - name: installing mysql
      apt:
        name: mysql
        state: present
      when: ansible_distribution== 'ubuntu'

    - name: starting mariadb
      service:
        name: mariadb
        state: started
      when: ansible_distribution== 'Amazon'

    - name: starting mysql
      service:
        name: mysql
        state: started
      when: ansible_distribution== 'ubuntu'

    - name: insaling php
      yum: name=php state=present
      when: ansible_distribution== 'Amazon'

    - name: intaling php
      apt: name=php state=present
      when: ansible_distribution== 'ubuntu'

    - name: insaling php-fpm
      yum: name=php-fpm state=present
      when: ansible_distribution== 'Amazon'
    
    - name: intaling php-fpm
      apt: name=php state=present
      when: ansible_distribution== 'ubuntu'

    - name: starting php-fpm
      service: name=php-fpm state=started
      when: ansible_distribution== 'Amazon'

    - name: starting php-fpm
      service: name=php-fpm state=started
      when: ansible_distribution == 'ubuntu'

    - name: restart all
      service: name=nginx state=restarted
      when: ansible_distribution== 'Amazon'

    - name: restart all
      service: name=nginx state=restarted
      when: ansible_distribution== 'ubuntu'

